language: python
os:
  - linux
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r .travis_requirements.txt
  - pip install coverage
  - pip install pytest
# command to run tests
script:
  - python setup.py develop
